---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Install Avahi package ({{ item }})
  ansible.builtin.package:
    name: '{{ item }}'
  with_items: '{{ avahi_packages }}'
- name: Configure Avahi
  ansible.builtin.template:
    src: avahi-daemon.conf.j2
    dest: /etc/avahi/avahi-daemon.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart avahi
- name: Install Avahi service definitions
  ansible.builtin.template:
    src: service.j2
    dest: /etc/avahi/services/{{ item.name }}.service
    owner: root
    group: root
    mode: 0644
  vars:
    avahi_service_services: '{{ item.services }}'
  with_items: '{{ avahi_services }}'
  notify:
    - restart avahi
- name: Ensure service is running
  ansible.builtin.service:
    name: avahi-daemon
    state: started
